### ISSUE TITLE
is a leaderboard for nationalities of interest?

### ISSUE THREAD

**Issue by Djfe** [JaredKerim-Mozilla/leaderboard-server#68]
Should there be a leaderboard for nationalities (in contrast to regions)?

We could add a leaderboard for members that don't want to expose their nationality (in combination with their nickname)

**Comment by jaredkerim** [comment]
@Djfe Can you explain what you mean by nationalities?  

The initial design for the leaderboard supports a global ranking (all contributors ranked by number of observations), and a per country ranking (contributors which have made observations within a given country ranked by the number of those observations).  

Each country is defined by a spatial shape boundary, for instance:

http://thematicmapping.org/downloads/

A contributor who has agreed to participate in the leaderboard will appear in all rankings they have contributed to: the global ranking, and the per-country ranking for each country they've contributed to.

**Comment by Djfe** [comment]
Sure, I mean that it would be great to see which country has the most active stumblers
for example all my points would appear in the german ranking then (even if I stumble in Great Britain on vacation or something like that)
it would be grouped by the nationalities of the stumblers then (if the stumblers agree to share their nationality with MLS)

**Comment by jaredkerim** [comment]
@Djfe Each contribution (a set of observations of WifiCell towers) is marked with the location the observations are made to within a 1km x 1km square (to keep things from being too accurate).  If you made observations in Germany and in Great Britain, then you would appear in each of those countries leaderboards, ranked according to the number of observations you made in each country.  Both would contribute to your global ranking.  

An observation made in Great Britain would not contribute to your score or rank in Germany, or visa versa.  There is no plan to have the concept of 'nationality' stored for a contributor, or a 'nationality' based ranking/score, that would require additional information from the user and for the first pass of this system we're trying to keep it as simple as possible.  In the future we want to add more complex leaderboard types and competitions, and then we can explore more advanced leaderboards.  Thanks!
